apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-codeowners-in-repo
  title: Create a CODEOWNERS file
  description: Create a new PR with a basic CODEOWNERS file.
spec:
  owner: group:roadiehq/engineering
  type: file

  parameters:
    - title: Basic info
      required:
        - repoName
      properties:
        repoHost:
          type: string
          default: github.com
          ui:widget: hidden
        repoOrg:
          type: string
          default: roadiehq # Change this to match the name of your GitHub org
          ui:widget: hidden
        repoName:
          title: Repository name
          type: string

  steps:
    - id: fetchTemplate
      action: fetch:template
      input:
        url: ./skeleton
        templateFileExtension: .njk

    - id: createPullRequest
      name: create-pull-request
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoHost }}?owner=${{ parameters.repoOrg }}&repo=${{ parameters.repoName }}
        branchName: add-codeowners-${{ '' | now }}
        title: Add a CODEOWENERS file
        description: |
          This PR adds a basic CODEOWNERS file to this repository. It must be edited to be correct.

          [Learn about CODEOWNERS on GitHub](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)

          It was created via a [scaffolder template on Roadie](https://example.com).

  output:
    links:
      - title: View the pull request on GitHub
        icon: github
        url: ${{ steps['createPullRequest'].output.remoteUrl }}
      - title: Learn about CODEOWNERS
        icon: help
        url: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
