apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: update-json-file
  title: Update a json file
  description: Opens a PR with updates to a json file.

spec:
  owner: engineering
  type: example
  parameters:
    - title: Provide some simple information
      required: ['my-key', 'my-value']
      properties:
        my-key:
          title: My Key
          type: string
          description: Update my-key in the json file
        my-value:
          title: My Value
          type: string
          description: Value to assign to my-key

  steps:
    - id: update-file
      name: Update a json file
      action: json:merge
      input:
        # Path to the root of the repo of interest. You can also use the RepoUrlPicker to choose one.
        path: https://github.com/RoadieHQ/software-templates/tree/main/scaffolder-templates/

    - id: update
      name: Update
      action: roadiehq:utils:merge
      input:
        # This file must exist at this path in the repo referenced above
        path: update-json-file/my-file.json

    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=private-test-entities&owner=RoadieHQ
        title: Update my-file.json
        description: update description
        branchName: update-my-file # TODO parameterise?



