apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.repo_name }}
  title: ${{ values.website_name | title }}
  description: A static HTML website. Just like the good old days.
  links:
    - url: https://${{ values.repo_owner}}.github.io/${{ values.repo_name }}/
      title: Live website
  annotations:
    github.com/project-slug: ${{ values.repo_owner }}/${{ values.repo_name }}
    backstage.io/techdocs-ref: dir:.
    pagerduty.com/integration-key: ${{ values.pagerduty_integration_key }}
spec:
  type: website
  owner: engineering
  lifecycle: experimental
