apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: notify-slack-clients
  title: Notify Slack Clients
  description: Send a notification to all client external slack channels

spec:
  owner: user:ian.link
  type: none
  parameters:
    - title: Define the message
      required:
        - message
      properties:
        message:
          title: message
          type: string

  steps:
    - id: send-message
      name: Send message to {client name}
      action: http:backstage:request
      input:
        method: POST
        header: 
          - Content-type: application/json
        path: /proxy/client-notification/TUU4TL8JZ/B06F0DMNAET/uDYlSkU8b4vVH8SMFuU9HF3l
        body:
          text: "${{ parameters.message}}" #'{ type: section, text: { type: mrkdwn, text: ${{ parameters.message}} }'
    - id: log request
      name: Message Sent
      action: debug:log
      input:
        message: "Request was: ${{ steps['send-message'].output. Body was: ${{ steps['send-message'].output.body "
  output:
    resp: Messages sent